#!/usr/bin/env bash

echo "This is a bootstrap script to install all the required tools and setup some basic stuff"

###
### Default in new macOS
###
# Enable FileVault
#if [[ `fdesetup status` != "FileVault is On." ]]; then
#  echo "Enabling File Vault"
#  sudo fdesetup enable
#  echo "Copy the recovery code in a safe place"
#  echo "Press any key to continue"
#  read continue
#else
#  echo "File Vault already enabled"
#fi

### Improve FileVault security by deleting the key from RAM when in standby mode
sudo pmset -a destroyfvkeyonstandby 1
# Change standby delay from 3h to 2h
sudo pmset -a standbydelay 7200
# Change ibernation mode.
sudo pmset -a hibernatemode 25
#sudo pmset -a hibernatemode 3

# Install XCode
if [[ $(/usr/bin/gcc 2>&1) =~ "no developer tools were found" ]] || [[ ! -x /usr/bin/gcc ]]; then
  echo "Install XCode CLI Tools"
  xcode-select --install
  echo "Wait for XCode CLI Tools to finish install"
  echo "When finished press RETURN to continue"
  read CONTINUE
else
  echo "XCode CLI Tools already installed"
fi
# Accept XCode License
sudo xcodebuild -license accept


# Download and install Homebrew
if [[ ! -x /usr/local/bin/brew ]]; then
  echo "Installing Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  export PATH=/usr/local/bin:$PATH
else
  echo "Homebrew already installed"
fi


# Installing mas
brew install mas


# Clone dotfiles repo
echo "Cloning dotfiles"
git clone https://github.com/biosan/dotfiles.git ~/.dotfiles

echo "Bootstrap completed"
echo "Please sign-in with your AppleID (required for 'mas')"
echo "Then run '~/.dotfiles/_configure' to start configuring your Mac"
