
# Basic stuff not available on Nix
brew m-cli

# Casks (mostly big GUI apps)
cask alfred
cask amethyst
cask bitwarden
cask chromium
cask docker
cask dozer
cask dropbox
cask firefox
cask gitup
cask handbrake
cask iina
cask imageoptim
cask imazing-mini
cask wintellij-idea-ce
cask karabiner-elements
cask keka
cask kicad
cask logitech-options
cask macdown
cask omnifocus
cask openemu
cask pycharm
cask qmk-toolbox
cask signal
cask virtualbox
cask visual-studio-code
cask webstorm
cask zerotier-one

# Mac App Store stuff (mostly big GUI apps)

# Install fonts
cask font-abril-fatface
cask font-comfortaa
cask font-computer-modern
cask font-dosis
cask font-fira-code
cask font-firacode-nerd-font
cask font-firacode-nerd-font-mono
cask font-gabriela
cask font-gohu-nerd-font
cask font-gohu-nerd-font-mono
cask font-goudy-bookletter1911
cask font-hack
cask font-hack-nerd-font
cask font-ibm-plex
cask font-josefin-sans
cask font-lobster
cask font-lobster-two
cask font-montserrat
cask font-oranienbaum
cask font-playfair-display
cask font-playfair-display-sc
cask font-profont-nerd-font-mono
cask font-profontx
cask font-proggyclean-nerd-font
cask font-proggyclean-nerd-font-mono
cask font-raleway
cask font-ribeye-marrow
cask font-rochester
cask font-sacramento
cask font-terminus
cask font-terminus-nerd-font
cask font-terminus-nerd-font-mono
cask font-vidaloka
cask font-work-sans

