
# Basic stuff not available on Nix
brew "m-cli"

# Casks (mostly big GUI apps)
cask "amethyst"
cask "chromium"
cask "docker"
cask "dozer"
cask "firefox"
cask "handbrake"
cask "iina"
cask "imageoptim"
cask "imazing-mini"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "keka"
#cask "kicad"
cask "macdown"
cask "omnifocus"
cask "openemu"
cask "homebrew/cask-drivers/qmk-toolbox"
cask "signal"
#cask "virtualbox" # As of 2020-12-31 installation fails
cask "visual-studio-code"

# Mac App Store stuff (mostly big GUI apps)
mas "Affinity Designer", id: 824171161
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "GoodNotes", id: 1444383602
mas "Reeder", id: 880001334
mas "SafariMarkdownLinker", id: 1289119450
mas "Tailscale", id: 1475387142
mas "Todoist", id: 585829637
mas "WireGuard", id: 1451685025

# Install fonts
tap "homebrew/cask-fonts"
brew "svn" # Unfortunately some fonts formulas use SVN
cask "font-abril-fatface"
cask "font-comfortaa"
cask "font-computer-modern"
cask "font-dosis"
cask "font-fantasque-sans-mono-nerd-font"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-gabriela"
#cask "font-gohu-nerd-font"
#cask "font-gohu-nerd-font-mono"
#cask "font-goudy-bookletter1911"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-ibm-plex"
cask "font-josefin-sans"
cask "font-lobster"
cask "font-lobster-two"
cask "font-montserrat"
cask "font-oranienbaum"
cask "font-playfair-display"
cask "font-playfair-display-sc"
cask "font-profontx"
#cask "font-proggyclean-nerd-font"
#cask "font-proggyclean-nerd-font-mono"
cask "font-raleway"
cask "font-ribeye-marrow"
cask "font-rochester"
cask "font-sacramento"
cask "font-terminus"
#cask "font-terminus-nerd-font"
#cask "font-terminus-nerd-font-mono"
cask "font-vidaloka"
cask "font-work-sans"

